nelmio_api_doc:
    documentation:
        info:
            title: 'User Service API'
            description: 'OpenAPI documentation for the User Service'
            version: '1.0.0'
        servers:
            - url: '/'
