name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Warm cache (user-service)
        uses: docker/build-push-action@v5
        with:
          context: ./user-service
          push: false
          tags: tmp/user-service:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Warm cache (notification-service)
        uses: docker/build-push-action@v5
        with:
          context: ./notification-service
          push: false
          tags: tmp/notification-service:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Make up (build and start stack)
        run: make up

      - name: Wait for services to be ready
        run: |
          set -e
          echo "Waiting for services to start..."
          sleep 30
          
          echo "Checking service health..."
          for i in {1..30}; do
            echo "Attempt $i/30..."
            
            # Check if gateway is responding
            if curl -fsS http://localhost:8082/health >/dev/null 2>&1; then
              echo "✅ Gateway health check passed"
              
              # Also verify services are accessible
              if curl -fsS http://localhost:8080/health >/dev/null 2>&1 && \
                 curl -fsS http://localhost:8081/health >/dev/null 2>&1; then
                echo "✅ All services are healthy"
                exit 0
              fi
            fi
            
            echo "Services not ready yet, waiting..."
            sleep 5
          done
          
          echo "❌ Services failed to become healthy within timeout"
          echo "Checking container status:"
          make ps || true
          echo "Gateway logs:"
          make logs-gw || true
          exit 1

      - name: Migrate user-service
        run: make migrate

      - name: Install script dependencies (jq)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Smoke test
        run: make smoke

      - name: E2E test
        run: make e2e

      - name: Export OpenAPI specs
        run: bash scripts/export-openapi.sh

      - name: Upload OpenAPI artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openapi-specs
          path: docs/*.openapi.json

      - name: Show container statuses
        run: make ps || true

      - name: Gather logs on failure
        if: failure()
        run: make logs || true

      - name: Tear down
        if: always()
        run: make down
