name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Warm cache (user-service)
        uses: docker/build-push-action@v5
        with:
          context: ./user-service
          push: false
          tags: tmp/user-service:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Warm cache (notification-service)
        uses: docker/build-push-action@v5
        with:
          context: ./notification-service
          push: false
          tags: tmp/notification-service:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Make up (build and start stack)
        run: make up

      - name: Wait for gateway health
        run: |
          set -e
          for i in {1..60}; do
            if curl -fsS http://localhost:8082/health >/dev/null; then
              echo "Gateway is up"
              exit 0
            fi
            sleep 2
          done
          echo "Gateway failed to become healthy" >&2
          exit 1

      - name: Migrate user-service
        run: make migrate

      - name: Install script dependencies (jq)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Smoke test
        run: make smoke

      - name: E2E test
        run: make e2e

      - name: Export OpenAPI specs
        run: bash scripts/export-openapi.sh

      - name: Upload OpenAPI artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openapi-specs
          path: docs/*.openapi.json

      - name: Show container statuses
        run: make ps || true

      - name: Gather logs on failure
        if: failure()
        run: make logs || true

      - name: Tear down
        if: always()
        run: make down
