# Custom services configuration overlay for container build
parameters: {}

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'

  # Ensure controllers are public and properly tagged
  App\Controller\:
    resource: '../src/Controller/'
    public: true
    tags: ['controller.service_arguments']
